import { useLocale } from 'next-intl';

const fr = {
  title: 'Documents officiels',
  description: 'Émissions, téléchargements et vérification des documents de l’établissement.',
  generate: 'Générer un document',
  download: 'Télécharger le PDF',
  preview: 'Aperçu',
  revoke: 'Révoquer',
  reissue: 'Réémettre',
  search: 'Rechercher un document',
  sourceSearch: 'Rechercher une source',
  source: 'Source officielle',
  choose: 'Sélectionner une source',
  type: 'Type de document',
  locale: 'Langue',
  reference: 'Numéro',
  holder: 'Titulaire',
  status: 'Statut',
  date: 'Date',
  actions: 'Actions',
  loading: 'Chargement…',
  empty: 'Aucun document pour cette sélection.',
  forbidden: 'Vous ne disposez pas des droits nécessaires.',
  error: 'Impossible de terminer cette opération. Vérifiez la source, vos droits et réessayez.',
  reason: 'Motif de révocation',
  confirm: 'Confirmer',
  cancel: 'Annuler',
  history:
    'La réémission crée un nouveau document. Le précédent conserve son état et son historique.',
  sourceHint:
    'Seules les données enregistrées et éligibles sont utilisées. Affinez la recherche au-delà de 50 sources.',
  revokedHint: 'Document révoqué — copie historique, non valide.',
  print: 'Carte ID-1 · 85,60 × 53,98 mm · imprimer à 100 %',
  photo: 'Photo indisponible',
  year: 'Année scolaire',
  class: 'Classe',
  matricule: 'Matricule',
  verify: 'Vérification du document',
  verificationHint:
    'Cette vérification atteste une émission GestSchool, sans constituer une signature électronique qualifiée.',
  invalid: 'Document invalide ou introuvable.',
  school: 'Établissement',
  issued: 'Émis le',
  PENDING: 'En attente',
  PROCESSING: 'Génération en cours',
  READY: 'Prêt',
  FAILED: 'Échec',
  REVOKED: 'Révoqué',
  VALID: 'Valide',
  REPORT_CARD: 'Bulletin scolaire',
  TRANSCRIPT: 'Relevé de notes',
  SCHOOL_CERTIFICATE: 'Certificat de scolarité',
  ENROLLMENT_CERTIFICATE: 'Certificat d’inscription',
  STUDENT_CARD: 'Carte élève',
  RECEIPT: 'Reçu de paiement',
  templates: 'Modèles et versions',
  publish: 'Publier une nouvelle version',
  name: 'Nom du modèle',
  accent: 'Couleur principale',
  footer: 'Pied de page',
  templateHint: 'Une version publiée est immuable. Les anciens documents ne sont pas modifiés.',
  all: 'Tous les types',
};
type Copy = { [K in keyof typeof fr]: string };
const en: Copy = {
  title: 'Official documents',
  description: 'Issue, download and verify school documents.',
  generate: 'Generate a document',
  download: 'Download PDF',
  preview: 'Preview',
  revoke: 'Revoke',
  reissue: 'Reissue',
  search: 'Search documents',
  sourceSearch: 'Search sources',
  source: 'Official source',
  choose: 'Select a source',
  type: 'Document type',
  locale: 'Language',
  reference: 'Number',
  holder: 'Holder',
  status: 'Status',
  date: 'Date',
  actions: 'Actions',
  loading: 'Loading…',
  empty: 'No documents for this selection.',
  forbidden: 'You do not have the required permissions.',
  error: 'Unable to complete this operation. Check the source and your permissions, then retry.',
  reason: 'Revocation reason',
  confirm: 'Confirm',
  cancel: 'Cancel',
  history: 'Reissuing creates a new document. The previous document keeps its status and history.',
  sourceHint: 'Only eligible records are used. Refine your search beyond 50 sources.',
  revokedHint: 'Revoked document — historical copy, not valid.',
  print: 'ID-1 card · 85.60 × 53.98 mm · print at 100%',
  photo: 'Photo unavailable',
  year: 'Academic year',
  class: 'Class',
  matricule: 'Student number',
  verify: 'Document verification',
  verificationHint: 'This verifies a GestSchool issuance, not a qualified electronic signature.',
  invalid: 'Invalid or unknown document.',
  school: 'School',
  issued: 'Issued on',
  PENDING: 'Pending',
  PROCESSING: 'Processing',
  READY: 'Ready',
  FAILED: 'Failed',
  REVOKED: 'Revoked',
  VALID: 'Valid',
  REPORT_CARD: 'Report card',
  TRANSCRIPT: 'Academic transcript',
  SCHOOL_CERTIFICATE: 'School attendance certificate',
  ENROLLMENT_CERTIFICATE: 'Enrollment certificate',
  STUDENT_CARD: 'Student card',
  RECEIPT: 'Payment receipt',
  templates: 'Templates and versions',
  publish: 'Publish a new version',
  name: 'Template name',
  accent: 'Primary colour',
  footer: 'Footer',
  templateHint: 'Published versions are immutable. Existing documents are not changed.',
  all: 'All types',
};
const ar: Copy = {
  title: 'الوثائق الرسمية',
  description: 'إصدار وثائق المؤسسة وتنزيلها والتحقق منها.',
  generate: 'إنشاء وثيقة',
  download: 'تنزيل PDF',
  preview: 'معاينة',
  revoke: 'إلغاء الصلاحية',
  reissue: 'إعادة الإصدار',
  search: 'البحث عن وثيقة',
  sourceSearch: 'البحث عن مصدر',
  source: 'المصدر الرسمي',
  choose: 'اختر مصدراً',
  type: 'نوع الوثيقة',
  locale: 'اللغة',
  reference: 'الرقم',
  holder: 'صاحب الوثيقة',
  status: 'الحالة',
  date: 'التاريخ',
  actions: 'الإجراءات',
  loading: 'جار التحميل…',
  empty: 'لا توجد وثائق لهذا الاختيار.',
  forbidden: 'ليست لديك الصلاحيات المطلوبة.',
  error: 'تعذر إتمام العملية. تحقق من المصدر والصلاحيات ثم أعد المحاولة.',
  reason: 'سبب إلغاء الصلاحية',
  confirm: 'تأكيد',
  cancel: 'إلغاء',
  history: 'إعادة الإصدار تنشئ وثيقة جديدة وتحافظ الوثيقة السابقة على حالتها وسجلها.',
  sourceHint: 'تستخدم السجلات المؤهلة فقط. حدد البحث إذا تجاوز عدد المصادر خمسين.',
  revokedHint: 'وثيقة ملغاة الصلاحية — نسخة تاريخية غير صالحة.',
  print: 'بطاقة ID-1 · 85.60 × 53.98 مم · طباعة بنسبة 100٪',
  photo: 'الصورة غير متوفرة',
  year: 'السنة الدراسية',
  class: 'الفصل',
  matricule: 'رقم الطالب',
  verify: 'التحقق من الوثيقة',
  verificationHint: 'يتحقق هذا من إصدار GestSchool ولا يمثل توقيعاً إلكترونياً مؤهلاً.',
  invalid: 'وثيقة غير صالحة أو غير موجودة.',
  school: 'المؤسسة',
  issued: 'تاريخ الإصدار',
  PENDING: 'قيد الانتظار',
  PROCESSING: 'جار الإنشاء',
  READY: 'جاهزة',
  FAILED: 'فشل',
  REVOKED: 'ملغاة الصلاحية',
  VALID: 'صالحة',
  REPORT_CARD: 'كشف النتائج الدراسية',
  TRANSCRIPT: 'كشف الدرجات',
  SCHOOL_CERTIFICATE: 'شهادة مدرسية',
  ENROLLMENT_CERTIFICATE: 'شهادة التسجيل',
  STUDENT_CARD: 'بطاقة الطالب',
  RECEIPT: 'إيصال الدفع',
  templates: 'القوالب والإصدارات',
  publish: 'نشر إصدار جديد',
  name: 'اسم القالب',
  accent: 'اللون الرئيسي',
  footer: 'تذييل الصفحة',
  templateHint: 'الإصدارات المنشورة ثابتة ولا تتغير الوثائق السابقة.',
  all: 'جميع الأنواع',
};
export function useDocumentCopy(): Copy {
  const locale = useLocale();
  return locale === 'ar' ? ar : locale === 'en' ? en : fr;
}
